In [2]:
import pandas as pd

# 将CSV文件导入为DataFrame
df = pd.read_csv('SMLnew2.csv')

# 显示DataFrame的前几行
print(df.head())

             LOG_ID            PAT_ID               MRN  Cardiovascular   LOS  \
0  d754f06a7d973a26  837532f458d9c660  0b8de903ea63082a             0.0   1.0
1  5a95970d5c8fc355  fd18a41f136ed278  0a8b72c1cec4ae47             0.0  10.0
2  138d44a06cf4b57f  fd18a41f136ed278  0a8b72c1cec4ae47             0.0  10.0
3  82372dc4703ea1b0  648781c95d863ec6  e0cb9244fedd1ac7             0.0   3.0
4  4b6aabaf62e85c0a  d1d7b9ddc4962cdf  3918b79e03cefe27             0.0   3.0

   ICU_ADMIN_FLAG      HEIGHT    WEIGHT  SEX  ASA_RATING_C  Abnormal Flag  \
0               0  187.960000   92.6991    1           2.0       0.355511
1               1  168.251459  100.9530    1           3.0       0.355511
2               1  168.251459  100.9530    1           3.0       0.355511
3               1  160.020000   70.1064    0           2.0       0.355511
4               1  168.251459   86.3922    1           2.0       0.000000

   ORDER_STATUS_IMPACT  discharge_risk_level  BIRTH_DATE  PATIENT_CLASS_GROUP  \
0                  1.0                     1          67                    1
1                  1.0                     1          57                    0
2                  1.0                     1          57                    0
3                  1.0                     1          69                    0
4                  2.0                     3          50                    0

   PATIENT_CLASS_NM
0                 2
1                 1
2                 0
3                 1
4                 1

In [4]:
df.drop(columns=['PATIENT_CLASS_GROUP'])

,LOG_ID,PAT_ID,MRN,Cardiovascular,LOS,ICU_ADMIN_FLAG,HEIGHT,WEIGHT,SEX,ASA_RATING_C,Abnormal Flag,ORDER_STATUS_IMPACT,discharge_risk_level,BIRTH_DATE,PATIENT_CLASS_NM
0,d754f06a7d973a26,837532f458d9c660,0b8de903ea63082a,0.0,1.0,0,187.960000,92.6991,1,2.0,0.355511,1.0,1,67,2
1,5a95970d5c8fc355,fd18a41f136ed278,0a8b72c1cec4ae47,0.0,10.0,1,168.251459,100.9530,1,3.0,0.355511,1.0,1,57,1
2,138d44a06cf4b57f,fd18a41f136ed278,0a8b72c1cec4ae47,0.0,10.0,1,168.251459,100.9530,1,3.0,0.355511,1.0,1,57,0
3,82372dc4703ea1b0,648781c95d863ec6,e0cb9244fedd1ac7,0.0,3.0,1,160.020000,70.1064,0,2.0,0.355511,1.0,1,69,1
4,4b6aabaf62e85c0a,d1d7b9ddc4962cdf,3918b79e03cefe27,0.0,3.0,1,168.251459,86.3922,1,2.0,0.000000,2.0,3,50,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1599,8116aa4a100ceee8,478a3cd8857cc055,72accda5075f7a39,1.0,34.0,1,165.100000,72.1698,1,3.0,0.000000,0.0,1,69,2
1600,3c146c502e1e249d,fa6ec9ad3f5f1466,2408210232a3e06b,0.0,1.0,0,154.940000,70.1592,0,3.0,2.000000,1.0,1,78,2
1601,cecd35a626c55d0c,b9878cd048a80cb3,5b9cf2e5349171e8,1.0,77.0,1,166.370000,52.2756,0,3.0,0.000000,0.0,1,61,0
1602,3333ade5695c0b55,2f091eb1b00105d4,c280ccc5e979b4ef,0.0,7.0,1,162.560000,71.4291,0,3.0,0.000000,0.0,1,54,0
1603,c34b85c0cf941d8a,b5838d1cdf37c09c,d7946ede59551209,1.0,7.0,1,154.940000,45.5028,0,3.0,1.000000,0.0,2,61,0

In [5]:
df.to_csv('SMLnew3.csv', index=False)